
import { arraySidebar } from "vuepress-theme-hope";

export const css = arraySidebar([
  "",
  "box-model",
  "selectors",
  "the-cascade",
  "specificity",
  "inheritance",
  "color",
  "sizing",
  "layout",
  "flexbox",
  "grid",
  "logical-properties",
  "spacing",
  "pseudo-elements",
  "pseudo-classes",
  "borders",
  "shadows",
  "focus",
  "z-index",
  "functions",
  "gradients",
  "animations",
  "filters",
  "blend-modes",
  "lists",
  "transitions",
  "overflow",
  "backgrounds",
  "typography",
  "conclusion", 
]);
